source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

target 'PinLayoutSample'

pod 'PinLayout'
pod 'SDWebImage','5.8.4'

post_install do |installer|       

   installer.pods_project.targets.each do |target| 

     puts 'PinLayoutSample'
     
   end
end
