source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

target 'PinLayoutSample'

pod 'PinLayout'


post_install do |installer|       

   installer.pods_project.targets.each do |target| 

     puts 'PinLayoutSample'

   end
end